{{- if not .Values.network }}
{{- $appValues := $.Values.remoteHeadless }}
{{- range $idx := until (int $appValues.count) }}
{{- $index := add $idx 1 }}
{{- if $appValues.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Release.Name }}-remote-headless-{{ $index }}
  namespace: argocd
spec:
  project: {{ $.Release.Name }}
  source:
    repoURL: https://github.com/eseiker/9c-infra.git
    targetRevision: modular-headless
    path: charts/headless
    helm:
      values: |-
        namespace: {{ $.Release.Name }}

        {{- with (merge $appValues $.Values.global) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Release.Name }}
---
{{- end }}
{{- end }}
{{- end }}
