name: Update planets config

on:
  workflow_dispatch:
  pull_request_target:
    paths:
      - planets/*.json
    branches:
      - main
    types:
      - closed

jobs:
  validate-planets-config:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/validate-planets.yaml
  update-planets-config:
    needs: [validate-planets-config]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: dorny/paths-filter@v3
        id: paths
        with:
          list-files: shell
          filters: |
            planets: planets/*.json
      - run: |
          FILES=(${{ steps.paths.outputs.planets_files }})
          for FILE in "${FILES[@]}"; do
            echo "$FILE"
          done
