name: Validate planets config

on:
  workflow_call:
  pull_request:
    paths:
      - planets/index.json

jobs:
  validate-planets-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno -A .github/scripts/validate-planets.js planets/index.json
